# Generated by Django 5.0.4 on 2024-04-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100, verbose_name='Name')),
                ('healing_power', models.IntegerField(default=0, verbose_name='Healing Power')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Level')),
                ('health', models.IntegerField(default=10, verbose_name='Health')),
                ('strength', models.IntegerField(default=1, verbose_name='Stength')),
                ('defense', models.IntegerField(default=1, verbose_name='Defense')),
                ('experience', models.IntegerField(default=0, verbose_name='Experience')),
                ('goldpieces', models.IntegerField(default=100, verbose_name='GoldPieces')),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100, verbose_name='Name')),
                ('level', models.IntegerField(default=1, verbose_name='Level')),
                ('health', models.IntegerField(default=5, verbose_name='Health')),
                ('strength', models.IntegerField(default=1, verbose_name='Stength')),
                ('defense', models.IntegerField(default=0, verbose_name='Defense')),
                ('experience', models.IntegerField(default=20, verbose_name='Experience')),
                ('gold_pieces', models.IntegerField(default=7, verbose_name='Gold_pieces')),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgame.location')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgame.healingitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgame.player')),
            ],
        ),
    ]
