# Generated by Django 5.0.4 on 2024-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='Nothing', max_length=100, verbose_name='Username'),
        ),
    ]
