# Generated by Django 5.0.4 on 2024-04-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0007_player_attribute_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='experience_treshhold',
            field=models.IntegerField(default=100, verbose_name='Experience Threshold'),
        ),
        migrations.AlterField(
            model_name='player',
            name='attribute_points',
            field=models.IntegerField(default=3, verbose_name='Attribute points'),
        ),
    ]
