# Generated by Django 5.0.4 on 2024-04-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0008_player_experience_treshhold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='experience_treshhold',
            new_name='experience_treshold',
        ),
    ]
