# Generated by Django 5.0.4 on 2024-04-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0009_rename_experience_treshhold_player_experience_treshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='experience_treshold',
            new_name='experience_threshold',
        ),
    ]
