# Generated by Django 5.0.4 on 2024-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0010_rename_experience_treshold_player_experience_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_healh',
            field=models.IntegerField(default=10, verbose_name='Current health'),
        ),
    ]
