# Generated by Django 5.0.4 on 2024-04-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0011_player_current_healh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_healh',
            new_name='health_threshold',
        ),
    ]
