# Generated by Django 5.0.4 on 2024-04-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0013_rename_health_threshold_player_maximum_health'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='Location',
            new_name='location',
        ),
    ]
