# Generated by Django 5.0.4 on 2024-04-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0014_rename_location_enemy_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='location',
            new_name='Location',
        ),
    ]
