# Generated by Django 5.0.4 on 2024-04-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0015_rename_location_enemy_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Items',
        ),
    ]
