# Generated by Django 5.0.4 on 2024-04-16 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0016_rename_inventory_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item',
        ),
        migrations.RemoveField(
            model_name='items',
            name='player',
        ),
        migrations.AddField(
            model_name='items',
            name='item_name',
            field=models.CharField(default='nothing', max_length=100, verbose_name='Item name'),
        ),
        migrations.AddField(
            model_name='items',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HealingItem',
        ),
    ]
