# Generated by Django 5.0.4 on 2024-04-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0018_items_healing_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_type',
            field=models.CharField(default='nothing', max_length=100, verbose_name='Item type'),
        ),
    ]
