# Generated by Django 5.0.4 on 2024-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0020_alter_items_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='Location',
            new_name='location',
        ),
    ]
