# Generated by Django 5.0.4 on 2024-04-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0022_citylocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumablesMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_buy_price', models.IntegerField(default=50, verbose_name='Buy price')),
                ('item_sell_price', models.IntegerField(default=50, verbose_name='Sell price')),
                ('healing_item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bgame.items')),
            ],
        ),
    ]
