# Generated by Django 5.0.4 on 2024-04-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0025_remove_player_item_name_items_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='username',
        ),
    ]
