# Generated by Django 5.0.4 on 2024-04-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0026_remove_items_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumablesmarketplace',
            name='item_buy_price',
        ),
        migrations.RemoveField(
            model_name='consumablesmarketplace',
            name='item_sell_price',
        ),
        migrations.AddField(
            model_name='items',
            name='item_buy_price',
            field=models.IntegerField(default=50, verbose_name='Buy price'),
        ),
        migrations.AddField(
            model_name='items',
            name='item_sell_price',
            field=models.IntegerField(default=50, verbose_name='Sell price'),
        ),
    ]
