# Generated by Django 5.0.4 on 2024-04-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0027_remove_consumablesmarketplace_item_buy_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsumablesMarketplace',
        ),
    ]
