# Generated by Django 5.0.4 on 2024-04-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0028_delete_consumablesmarketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='store_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bgame.citylocation'),
        ),
    ]
