# Generated by Django 5.0.4 on 2024-04-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0029_items_store_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citylocation',
            old_name='name',
            new_name='city_location_name',
        ),
    ]
