# Generated by Django 5.0.4 on 2024-04-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0031_alter_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bgame.player'),
        ),
    ]
