# Generated by Django 5.0.4 on 2024-04-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0032_items_item_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_owner',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgame.items')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgame.player')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='owners',
            field=models.ManyToManyField(through='bgame.Inventory', to='bgame.player'),
        ),
    ]
