# Generated by Django 5.0.4 on 2024-04-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0033_remove_items_item_owner_inventory_items_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
    ]
