# Generated by Django 5.0.4 on 2024-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0034_remove_items_quantity_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='defense_modifier',
            field=models.PositiveIntegerField(default=0, verbose_name='Defense bonus'),
        ),
        migrations.AddField(
            model_name='items',
            name='strength_modifier',
            field=models.PositiveIntegerField(default=0, verbose_name='Strenght bonus'),
        ),
    ]
