# Generated by Django 5.0.4 on 2024-04-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0035_items_defense_modifier_items_strength_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='defense_modifier',
            field=models.IntegerField(default=0, verbose_name='Defense bonus'),
        ),
        migrations.AlterField(
            model_name='items',
            name='strength_modifier',
            field=models.IntegerField(default=0, verbose_name='Strenght bonus'),
        ),
    ]
