# Generated by Django 5.0.4 on 2024-04-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0036_alter_items_defense_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_weapon_equiped',
            field=models.BooleanField(default=False, verbose_name='Weapon equiped'),
        ),
    ]
