# Generated by Django 5.0.4 on 2024-04-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0037_player_is_weapon_equiped'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_boots_equiped',
            field=models.BooleanField(default=False, verbose_name='Boots equiped'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_chest_armour_equiped',
            field=models.BooleanField(default=False, verbose_name='Armour equiped'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_gloves_equiped',
            field=models.BooleanField(default=False, verbose_name='Gloves equiped'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_helmet_equiped',
            field=models.BooleanField(default=False, verbose_name='Helmet equiped'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_leg_armour_equiped',
            field=models.BooleanField(default=False, verbose_name='Leg armour equiped'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_pet_equiped',
            field=models.BooleanField(default=False, verbose_name='Pet equiped'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_ring_equiped',
            field=models.BooleanField(default=False, verbose_name='Ring equiped'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_shield_equiped',
            field=models.BooleanField(default=False, verbose_name='Weapon equiped'),
        ),
    ]
