# Generated by Django 5.0.4 on 2024-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0038_player_is_boots_equiped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='health_modifier',
            field=models.IntegerField(default=0, verbose_name='Health modifier'),
        ),
    ]
