# Generated by Django 5.0.4 on 2024-04-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0040_itemmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemManager',
        ),
    ]
