# Generated by Django 5.0.4 on 2024-04-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0041_delete_itemmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='experience_threshold',
            field=models.FloatField(default=100, verbose_name='Experience Threshold'),
        ),
    ]
