# Generated by Django 5.0.4 on 2024-04-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0043_rename_gold_pieces_enemy_minimum_gold_pieces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='maximum_gold_pieces',
            field=models.IntegerField(default=20, verbose_name='Maximum_gold_pieces'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='minimum_gold_pieces',
            field=models.IntegerField(default=7, verbose_name='Minimum_gold_pieces'),
        ),
    ]
