# Generated by Django 5.0.4 on 2024-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0044_alter_enemy_maximum_gold_pieces_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totem_name', models.CharField(max_length=100, verbose_name='Totem')),
            ],
        ),
    ]
