# Generated by Django 5.0.4 on 2024-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0046_totem_prayer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='prayer_price',
        ),
        migrations.AddField(
            model_name='totem',
            name='defense_prayer',
            field=models.IntegerField(default=1000, verbose_name='Pray defense'),
        ),
        migrations.AddField(
            model_name='totem',
            name='health_prayer',
            field=models.IntegerField(default=1000, verbose_name='Pray health'),
        ),
        migrations.AddField(
            model_name='totem',
            name='strength_prayer',
            field=models.IntegerField(default=1000, verbose_name='Pray strength'),
        ),
    ]
