# Generated by Django 5.0.4 on 2024-04-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0047_remove_totem_prayer_price_totem_defense_prayer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totem',
            old_name='defense_prayer',
            new_name='defense_prayer_price',
        ),
        migrations.RenameField(
            model_name='totem',
            old_name='health_prayer',
            new_name='health_prayer_price',
        ),
        migrations.RenameField(
            model_name='totem',
            old_name='strength_prayer',
            new_name='strength_prayer_price',
        ),
    ]
