# Generated by Django 5.0.4 on 2024-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0048_rename_defense_prayer_totem_defense_prayer_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiseElder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='WiseElder', max_length=100, verbose_name='Elder')),
                ('knowledge_price', models.IntegerField(default=100, verbose_name='Price')),
                ('variable', models.IntegerField(default=0, verbose_name='Variable')),
                ('knowledge_1_unlocked', models.BooleanField(default=False)),
                ('knowledge_2_unlocked', models.BooleanField(default=False)),
                ('knowledge_3_unlocked', models.BooleanField(default=False)),
                ('knowledge_4_unlocked', models.BooleanField(default=False)),
                ('knowledge_5_unlocked', models.BooleanField(default=False)),
                ('knowledge_6_unlocked', models.BooleanField(default=False)),
                ('knowledge_7_unlocked', models.BooleanField(default=False)),
            ],
        ),
    ]
