# Generated by Django 5.0.4 on 2024-04-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0050_wiseelder_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bgame.player'),
        ),
    ]
