# Generated by Django 5.0.4 on 2024-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0052_alter_wiseelder_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiseelder',
            name='variable',
            field=models.IntegerField(default=0, verbose_name='Variable'),
        ),
    ]
