# Generated by Django 5.0.4 on 2024-04-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0054_alter_totem_defense_prayer_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_boots_equiped',
            new_name='is_boots_equipped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_chest_armour_equiped',
            new_name='is_chest_armour_equipped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_gloves_equiped',
            new_name='is_gloves_equipped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_helmet_equiped',
            new_name='is_helmet_equipped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_leg_armour_equiped',
            new_name='is_leg_armour_equipped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_pet_equiped',
            new_name='is_pet_equipped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_ring_equiped',
            new_name='is_ring_equipped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_shield_equiped',
            new_name='is_shield_equipped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_weapon_equiped',
            new_name='is_weapon_equipped',
        ),
    ]
