# Generated by Django 5.0.4 on 2024-05-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0056_rename_is_boots_equipped_player_is_boots_equiped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='helmed_defense_modifier',
            field=models.PositiveIntegerField(default=0, verbose_name='Helmet defense modifier'),
        ),
    ]
