# Generated by Django 5.0.4 on 2024-05-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0057_inventory_helmed_defense_modifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_chest_armour_equiped',
            new_name='is_chest_equiped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_leg_armour_equiped',
            new_name='is_leg_equiped',
        ),
    ]
