# Generated by Django 5.0.4 on 2024-05-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0058_rename_is_chest_armour_equiped_player_is_chest_equiped_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_chest_equiped',
            new_name='is_chest_armour_equiped',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_leg_equiped',
            new_name='is_leg_armour_equiped',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='helmed_defense_modifier',
        ),
    ]
